#cloud-config
package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - curl
  - containerd

runcmd:
  - hostnamectl set-hostname master-node-1
  - mkdir -p /etc/containerd
  - "containerd config default | tee /etc/containerd/config.toml > /dev/null"
  - sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
  - systemctl restart containerd
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - "echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' > /etc/apt/sources.list.d/kubernetes.list"
  - apt-get update
  - apt-get install -y kubelet kubeadm kubectl --allow-change-held-packages
  - apt-mark hold kubelet kubeadm kubectl
  - swapoff -a
  - sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  - modprobe overlay
  - modprobe br_netfilter
  - |
    cat <<EOF > /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-iptables  = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    net.ipv4.ip_forward                 = 1
    EOF
  - sysctl --system
  - kubeadm init --pod-network-cidr=10.244.0.0/16
  - mkdir -p /home/ubuntu/.kube
  - cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
  - chown ubuntu:ubuntu /home/ubuntu/.kube/config
  - export KUBECONFIG=/etc/kubernetes/admin.conf
  - kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  - kubectl get nodes
  - kubectl get pods --all-namespaces
  - kubeadm token create --print-join-command --ttl 0
