#cloud-config
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - curl
  - containerd

write_files:
  - path: /etc/containerd/config.toml
    content: |
      # Default containerd configuration
      [plugins]
        [plugins.cri]
          [plugins.cri.containerd]
            [plugins.cri.containerd.runtimes]
              [plugins.cri.containerd.runtimes.runc]
                [plugins.cri.containerd.runtimes.runc.options]
                  SystemdCgroup = true
    permissions: '0644'

runcmd:
  - hostname worker-node-1
  - systemctl restart containerd
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
  - apt-get update
  - apt-get install -y kubelet kubeadm kubectl --allow-change-held-packages
  - apt-mark hold kubelet kubeadm kubectl
  - swapoff -a
  - sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  - modprobe overlay
  - modprobe br_netfilter
  - |
    cat <<EOF > /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-iptables  = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    net.ipv4.ip_forward                 = 1
    EOF
  - sysctl --system
